### ISSUE TITLE
Getting 404 responses

### ISSUE THREAD

**Issue by johnknoop** [bringking/mailgun_csharp#1]
Hi

I'm trying to get a simple example working, basically copying the code from your readme file. But I get 404 responses back.

When I look at the response object, I can see that it tries to access this URL:

http://api.mailgun.net/v2/sandbox84ad848982dd4091b90a6aa05701b901.mailgun.org/messages

And when I'm inside Mailgun´s application, it suggests using the v3 API. I don't know if thats the issue maybe. If so, is there any way I can specify the API version (or maybe something like a base URL) for the MessageService?

Cheers

**Comment by bringking** [comment]
Sorry about that, your comment made me realize how limiting hardcoding that value could be. I updated it so you can pass in overrides in these commits -

043f68c23dd808fc0d1909bd0139bec46ea7e358
c9acf1ab9ffb45a1d75faf1ffb0fcd5a6d3ac24e
99df1ab5181dd4a9019a3b5a2d4496d4319859aa

I updated the Nuget packages to 0.4.0 for the MailgunService and 0.5.0 for the Mailgun.AspNet.Identity packages. I will update the README to reflect the changes. Let me know if you run into any more issues.

**Comment by johnknoop** [comment]
Well that was extremely quick response, I must say!

I'll give it a try - thanks

**Comment by johnknoop** [comment]
Hmm, now I get an exception when executing the HTTP request:

![mailgun](https://cloud.githubusercontent.com/assets/3394270/8292202/90b3264e-192e-11e5-9452-48bc3c17c166.png)

I just copied the base URL from the settings page in Mailgun:

![mailgun2](https://cloud.githubusercontent.com/assets/3394270/8292242/c8bbb060-192e-11e5-8f62-f3a07aac76b3.PNG)

Perhaps I'm doing something wrong?

**Comment by bringking** [comment]
Ah yeah, well the BaseAddress override should be specified as the "Host" portion of the UriBuilder, so in this case that is just -

"api.mailgun.net/v3"

The code uses the "UseSSL" flags + the baseAddress to build the full URL like so-

```
var buildUri = new UriBuilder
                {
                    Host = BaseAddress,
                    Scheme = UseSSl ? "https" : "http",
                    Path = string.Format("{0}/messages", workingDomain)
                };
```

**Comment by johnknoop** [comment]
Thanks, that helped =)
