### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by oxozle** [bringking/mailgun_csharp#11]
Hi. I'm using Mailgun a lot. I would like to port library to .net core and update with issues.
And update to NuGet
I'm from Saint-Petersburg also.

**Comment by bringking** [comment]
@oxozle okay great, I will add you as a collaborator!

**Comment by oxozle** [comment]
Hi,
Can I

1. Upload new version to repository with support of .net core and .net 462
2. Make new NuGet package with more .NET style name package (like `Mailgun`)

**Comment by bringking** [comment]
@oxozle I sent you an invite to be a collaborator. Let me check on the Nuget Permissions. I think you can create a new package and publish without me doing anything though
