### ISSUE TITLE
.Net Standard 2.0 and Nuget

### ISSUE THREAD

**Issue by tgourley** [bringking/mailgun_csharp#13]
Any plan for the project to be .Net Standard 2.0 and for an official Nuget package?

**Comment by oxozle** [comment]
As I see project already support .net core 2.0. We should turn on tests before publish to Nuget

**Comment by tgourley** [comment]
is there a timeliine for adding to nuget?

**Comment by leotsarev** [comment]
Hm, seems that nobody has capacity to setup test or CI pipeline.
I'm going to manually build and publish 0.7.0 with netstandard2 support if I won't meet any objections.
@bringking @oxozle ?
