### ISSUE TITLE
MailgunMessageService with MailgunMessageServiceOptions is not working

### ISSUE THREAD

**Issue by blopez2010** [bringking/mailgun_csharp#2]
According to usage described in readme file, the usage of:

```
MailgunMessageServiceOptions mailOptions = new MailgunMessageServiceOptions
{
    Domain = ConfigurationManager.AppSettings["EmailDomain"],
    ApiKey = ConfigurationManager.AppSettings["EmailSecretKey"],
    TestMode = Convert.ToBoolean(ConfigurationManager.AppSettings["EmailTestMode"]),
    DefaultFrom = new Recipient() { DisplayName = ConfigurationManager.AppSettings["EmailFromDisplayName"], Email = ConfigurationManager.AppSettings["EmailFromAddress"] }                
};

manager.EmailService = new MailgunMessageService(mailOptions);
```

Is throwing next error:

Method not found: 'Void Mailgun.Service.MessageService..ctor(System.String, Boolean, System.String)'.

[MissingMethodException: Method not found: 'Void Mailgun.Service.MessageService..ctor(System.String, Boolean, System.String)'.]
   Mailgun.AspNet.Identity.MailgunMessageService..ctor(IMailgunMessageServiceOptions options) +0
   Transforce.Web.ApplicationUserManager.Create(IdentityFactoryOptions`1 options, IOwinContext context) in D:\vaincRepos\GitHub\transforce\src\Transforce.Web\App_Start\IdentityConfig.cs:188
   Microsoft.AspNet.Identity.Owin.IdentityFactoryProvider`1.Create(IdentityFactoryOptions`1 options, IOwinContext context) +38
   Microsoft.AspNet.Identity.Owin.<Invoke>d__0.MoveNext() +120
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.AspNet.Identity.Owin.<Invoke>d__0.MoveNext() +417
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +170
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +166
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +81
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +30
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by leotsarev** [comment]
Let's close this issue as stale
