### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by rdev5** [bringking/mailgun_csharp#6]
Are you still looking for a maintainer?

I was considering starting up my own repo (and probably still will), but it would seem that with Mailgun's [web service API and RestSharp](https://documentation.mailgun.com/libraries.html#c), it's almost difficult to justify having a community-supported library. The repo I'll be building, however. will actually be used for a class I teach.

Either way, let me know.

**Comment by bringking** [comment]
@rdev5 yeah I would love someone to take this over, I don't use it anymore, thus it is increasingly hard to maintain. If you would like to maintain it, I will give you full access to the project
